name: Mike Hawkins
favicon: null
layout_spectrum: 0.3378542
typography_spectrum: 0.73639
title: Mike Hawkins
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2A486E'
    - '#3696AF'
    - '#010204'
    - '#540017'
    - '#CC0146'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
