layout_spectrum: 0.3378542
color:
  saturation: 0.5212713
  lightness: 0.8100358
  brandStrength: 1
  brandColors:
    - '#2A486E'
    - '#3696AF'
    - '#010204'
    - '#540017'
    - '#CC0146'
  rhythmicContrast: 0.9410251
typography_spectrum: 0.08803625
name: Mike Hawkins
